Translate glossary
gatsbyjs/gatsby-pl pull request #26
Opened 2020-02-14 07:38 UTC by lekterable

2020-02-15 23:09 UTC, jaknas requested changes
Kawał dobrej roboty 👏

2020-02-15 23:09 UTC, jaknas commented on docs/docs/glossary.md
> +[Środowisko](#environment) podczas pracy nad kodem. Jest ono obsługiwane poprzez [CLI](#cli) za pomocą komendy `gatsby develop` i zapewnia specjalistyczne raportowanie błędów oraz wiele dodatkowych f
```suggestion
[Środowisko](#environment) podczas pracy nad kodem. Jest ono obsługiwane poprzez [CLI](#cli) za pomocą komendy `gatsby develop` i zapewnia specjalistyczne raportowanie błędów oraz wiele dodatkowych funkcji, które przydadzą się podczas debugowania kodu przed zbudowaniem projektu dla [produkcji](#production-environment).
```

2020-02-15 23:09 UTC, jaknas commented on docs/docs/glossary.md
> +[Zmienne środowiskowe](/docs/environment-variables/) pozwalają na dostosowywanie zachowania Twojej aplikacji w zależności od jej [środowiska](#environment). Przykładowo podczas rozwijania oprogramowa
```suggestion
[Zmienne środowiskowe](/docs/environment-variables/) pozwalają na dostosowywanie zachowania Twojej aplikacji w zależności od jej [środowiska](#environment). Przykładowo podczas rozwijania oprogramowania możesz chcieć pobierać swoją zawartość z przejściowego systemu CMS i połączyć się z właściwym CMS, gdy już [zbudujesz](#build) swoją stronę. Za pomocą zmiennych środowiskowych możesz ustawić inny adres URL dla każdego środowiska.
```

2020-02-15 23:09 UTC, jaknas commented on docs/docs/glossary.md
> +Sposób organizacji plików. W przypadku Gatsby oznacza to, że pliki znajdują się w tym samym miejscu co kod witryny lub aplikacji, zamiast pobierać dane z zewnętrznego [źródła](#data-source). Najczęst
```suggestion
Sposób w jakim pliki są zorganizowane. W przypadku Gatsby oznacza to, że pliki znajdują się w tym samym miejscu co kod witryny lub aplikacji, zamiast pobierać dane z zewnętrznego [źródła](#data-source). Najczęstsze użycie systemu plików w Gatsby obejmuje zawartość zapisaną w plikach Markdown, obrazach, plikach danych i innych zasobach.
```

2020-02-15 23:09 UTC, jaknas commented on docs/docs/glossary.md
>  The practice of using JSON returned from the WordPress REST API as a [headless CMS](#headless-cms). It allows you to use WordPress to write and edit content that can be consumed by any client capable
```suggestion
Sposób w którym korzysta się z plików JSON otrzymanych z REST API WordPressa jako [headless CMS](#headless-cms). Pozwala Ci to używać WordPressa do pisania i edytowania zawartości, która następnie może być użyta przez jakiegokolwiek klienta zdolnego do parsowania formatu JSON
```
🤔

2020-02-15 23:09 UTC, jaknas commented on docs/docs/glossary.md
> +Gatsby korzysta z [węzłów danych](/docs/node-interface/) do reprezentowania pojedynczego elementu danych. A [źródło danych](#data-source) tworzy wiele węzłów.
```suggestion
Gatsby korzysta z [węzłów danych](/docs/node-interface/) do reprezentowania pojedynczego elementu danych. [Źródło danych](#data-source) tworzy wiele węzłów.
```

2020-02-15 23:09 UTC, jaknas commented on docs/docs/glossary.md
> +Paczką zazwyczaj nazywawy [javascriptowy](#javascript) program zawierający dodatkowe informacje odnośnie tego, w jaki sposób powinien być on używany i dystrybuowany, np. numer jego wersji. [NPM](#npm
```suggestion
Paczką zazwyczaj nazywamy [javascriptowy](#javascript) program zawierający dodatkowe informacje odnośnie tego, w jaki sposób powinien być on używany i dystrybuowany, np. numer jego wersji. [NPM](#npm) i [Yarn](#yarn) zarządzają i instalują paczki używane przez Twój projekt. [Gatsby](#gatsby) sam w sobie jest paczką.
```

2020-02-15 23:09 UTC, kleyu commented on docs/docs/glossary.md
> +[javascriptowa](#javascript) aplikacja, z której korzysta Gatsby aby spakować kod Twojej strony. Dzieje się to automatycznie podczas [budowania](#build).
```suggestion
[Javascriptowa](#javascript) aplikacja, z której korzysta Gatsby aby spakować kod Twojej strony. Dzieje się to automatycznie podczas [budowania](#build).
```

2020-02-16 21:55 UTC, lekterable commented on docs/docs/glossary.md
> +Sposób w jakim pliki są zorganizowane. W przypadku Gatsby oznacza to, że pliki znajdują się w tym samym miejscu co kod witryny lub aplikacji, zamiast pobierać dane z zewnętrznego [źródła](#data-sourc
```suggestion
Sposób w jaki pliki są zorganizowane. W przypadku Gatsby oznacza to, że pliki znajdują się w tym samym miejscu co kod witryny lub aplikacji, zamiast pobierać dane z zewnętrznego [źródła](#data-source). Najczęstsze użycie systemu plików w Gatsby obejmuje zawartość zapisaną w plikach Markdown, obrazy, pliki danych i inne zasoby.
```

2020-02-16 21:57 UTC, lekterable commented on docs/docs/glossary.md
> +Sposób w jakim pliki są zorganizowane. W przypadku Gatsby oznacza to, że pliki znajdują się w tym samym miejscu co kod witryny lub aplikacji, zamiast pobierać dane z zewnętrznego [źródła](#data-sourc
Zacommitowałem tę zmianę, ale wydaje mi się, że w takiej formie ma to większy sens. "Content" w wersji angielskiej także odnosił się tylko do plików markdown. Daj znać co myślisz @kleyu

2020-02-17 20:17 UTC, jaknas approved these changes
looks good to me

2020-03-17 15:53 UTC, merged