Translation of docs/gatsby-image
gatsbyjs/gatsby-pl pull request #44
Opened 2020-06-05 20:21 UTC by AleksanderSkubala

2020-06-12 11:43 UTC, mbiesiad requested changes
Mainly small typos, nice to have it fixed.

2020-06-12 11:43 UTC, mbiesiad commented on docs/docs/api-files.md
> +Gatsby używa 4 plików w głownym katalogu projektu do konfiguracji twojej strony oraz kontroli tego jak się zachowuje. Wszytskie z tych plików są opcjonalne.
Wszytskie z tych plików są opcjonalne.
change to:
Wszystkie z tych plików są opcjonalne.
// small typo

2020-06-12 11:43 UTC, mbiesiad commented on docs/docs/api-files.md
> +- [gatsby-browser.js](/docs/api-files-gatsby-browser) - Pozwala kontrolować to jak Gatsby zachowuje się w przeglądarce. Na przykład: reagowanie na zmiane podstrony przez użytkownika, lub wywoływanie
przez użytkownika, lub wywoływanie funkcji gdy użytkownik
change to:
przez użytkownika lub wywoływanie funkcji, gdy użytkownik
// missing comma before 'gdy' and redundant with 'lub'

2020-06-12 11:43 UTC, mbiesiad commented on docs/docs/gatsby-image.md
> +Typowym sposobem na pozyskiwanie obrazów jest instalacja i używanie `gatsby-source-file` do łączenia plików lokalnych, można również używać innych pluginów źródłowych, takich jak `gatsby-source-conte
`gatsby-source-file`
change to:
`gatsby-source-filesystem`

2020-06-12 11:43 UTC, mbiesiad commented on docs/docs/gatsby-image.md
> +Oprócz ustawień `gatsby-plugin-sharp` w` gatsby-config.js`, istnieją dodatkowe opcje zapytań, które dotyczą obrazów _fluid_, _fixed_ i _resized_:
w` gatsby-config.js`
change to:
w `gatsby-config.js`
// relocated space

2020-06-18 12:18 UTC, AleksanderSkubala commented
Changes done ;)

2020-06-19 17:42 UTC, mbiesiad approved these changes

2020-07-30 22:30 UTC, AleksanderSkubala commented
Is everything right with my PR? 😧

2020-08-11 17:06 UTC, AdamSiekierski commented
> Is everything right with my PR? 😧

Yea, but the code owners need to merge it. Give'em some time ;)

2020-08-11 17:30 UTC, maciekgrzybek commented
Hey guys sorry, I didn't have time to look into it. I'll check tomorrow.

2020-08-11 17:31 UTC, maciekgrzybek approved these changes

2020-08-11 17:31 UTC, merged

2020-08-11 18:49 UTC, mbiesiad commented
> Hey guys sorry, I didn't have time to look into it. I'll check tomorrow.

@maciekgrzybek  Sure, it's nice to have you here again! Take your time, have a nice rest! Best greetings