Translate docs/recipes/deploying-your site
gatsbyjs/gatsby-pl pull request #45
Opened 2020-06-11 23:19 UTC by marceleq27

2020-06-12 11:26 UTC, mbiesiad requested changes
Mainly few small typos, nice to have it fixed.

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +5. Upewnij się, że twoja strona wygląda tak samo używając komendy `gatsby build` jak i `gatsby develop`. Kiedy strona została zbudowana uruchom `gatsby serve`, możesz teraz przetestować jej finalny e
finalny efekt(i jeśli to potrzebne - poprawić), change to:
finalny efekt (i jeśli to potrzebne - poprawić)
// missing space

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +### Dodatkowe źródła
Sometimes is better to use 'Dodatkowe materiały'

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +- Sprawdź [dokumenty wdrożeniowe](/docs/deploying-and-hosting/) aby odnaleźć więcej informacji na temat konkretnych platform hostingowych oraz jak wykorzystując je - wdrożyć stronę.
[dokumenty wdrożeniowe](/docs/deploying-and-hosting/) aby odnaleźć więcej informacji
change to
[dokumenty wdrożeniowe](/docs/deploying-and-hosting/), aby odnaleźć więcej informacji
// missing comma

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +Wykorzystaj [`netlify-cli`](https://www.netlify.com/docs/cli/) aby wdrożyć swoją aplikację Gatsby bez opuszczania interfejsu konsoli.
the same - missing comma before 'aby'

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +- [Strona Gatsby](/docs/quick-start) z pojedyńczym komponentem `index.js`
change to:
pojedynczym komponentem
// small typo

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +5. Wybierz swoją [grupę](https://www.netlify.com/docs/teams/).
team vs group

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +Wykorzystaj [Now CLI](https://zeit.co/download) aby wdrożyć swoją aplikację Gatsby bez opuszczania interfejsu konsoli.
Missing comma before 'aby'.

2020-06-12 11:26 UTC, mbiesiad commented on docs/docs/recipes/deploying-your-site.md
> +4. Skonfigutuj `wrangler.toml`. Na początku dodaj pole [account ID](https://developers.cloudflare.com/workers/quickstart/#account-id-and-zone-id) a następnie
Skonfigutuj `wrangler.toml`.
change to
Skonfiguruj `wrangler.toml`.
// small typo

2020-06-12 21:24 UTC, marceleq27 commented
Hi, I've made changes, thanks for your help 🙂

2020-06-12 21:49 UTC, mbiesiad approved these changes

2020-08-11 20:53 UTC, maciekgrzybek approved these changes

2020-08-11 20:53 UTC, merged