Translate docs/index
gatsbyjs/gatsby-pl pull request #47
Opened 2020-07-31 14:09 UTC by jakex7

2020-08-11 21:24 UTC, maciekgrzybek requested changes

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/api-files-gatsby-node.md
> +Kod z pliku `gatsby-node.js` jest uruchamiany raz, w trakcie budowania witryny. Możesz go użyć do dynamicznego tworzenia stron, dodawania punktów (nodes) GraphQL lub reagowania na zdarzenia procesu b
Jak wspomniane w innym PR, nie odmieniamy Gatsby.

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/api-files-gatsby-node.md
> +Kod z pliku `gatsby-node.js` jest uruchamiany raz, w trakcie budowania witryny. Możesz go użyć do dynamicznego tworzenia stron, dodawania punktów (nodes) GraphQL lub reagowania na zdarzenia procesu b
```suggestion
Kod z pliku `gatsby-node.js` jest uruchamiany raz, w trakcie budowania witryny. Możesz go użyć do dynamicznego tworzenia stron, dodawania punktów (nodes) GraphQL lub reagowania na zdarzenia procesu budowania. Aby korzystać z [Gatsby Node API](/docs/node-apis/), stwórz plik o nazwie `gatsby-node.js` w katalogu głównym projektu. Wyeksportuj API, które chcesz użyć w tym pliku.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/api-files-gatsby-node.md
> +Każdy Node API Gatsby'ego przekazuje [zestaw pomocniczych Punktów API](/docs/node-api-helpers/). Umożliwiają one dostęp do kilku metod, takich jak raportowanie, lub wywoływanie czynności, np. tworzen
Nie odmieniamy nazw wlasnych API.
```suggestion
Każdy z Node API Gatsby przekazuje [zestaw pomocniczy dla Node API](/docs/node-api-helpers/). Umożliwiają one dostęp do kilku metod, takich jak raportowanie, lub wywoływanie czynności, np. tworzenie nowych stron.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/api-files-gatsby-node.md
> +  result.data.allSamplePages.edges.forEach((edge) => {
Nie zmieniamy kodu.

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +Istnieją dwie możliwości, by zacząć z Gatsbym:
```suggestion
Istnieją dwie możliwości, by zacząć z Gatsby:
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +1. [Samouczek](/tutorial/): Instrukcje krok po kroku jak zainstalować Gatsby'ego i rozpocząć swój projekt: napisane dla ludzi bez doświadczenia z Gatsbym ani z programowaniem webowym, chociaż te zaso
```suggestion
1. [Samouczek](/tutorial/): Instrukcje krok po kroku jak zainstalować Gatsby i rozpocząć swój projekt: napisane dla ludzi bez doświadczenia z Gatsb ani z programowaniem webowym, chociaż te zasoby pomogły programistom na każdym poziomie umiejętności.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +2. [Szybki start](/docs/quick-start): Jednostronicowe podsumowanie, jak zainstalować Gatsby'ego i rozpocząć nowy projekt.
```suggestion
2. [Szybki start](/docs/quick-start): Jednostronicowe podsumowanie, jak zainstalować Gatsby i rozpocząć nowy projekt.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +1. [Przykłady i dobre praktyki](/docs/recipes/): Znajdź kilka szybkich odpowiedzi, jak wykonywać typowe zadania z Gatsbym.
```suggestion
1. [Przykłady i dobre praktyki](/docs/recipes/): Znajdź kilka szybkich odpowiedzi, jak wykonywać typowe zadania z Gatsby.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +2. Wybierz swoją ścieżkę i przejrzyj różne sekcje Dokumentacji Gatsby'ego:
```suggestion
2. Wybierz swoją ścieżkę i przejrzyj różne sekcje Dokumentacji Gatsby:
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +   - [Przewodniki](/docs/guides/): Dowiedz się o wielu tematach związanych z budowaniem stron z Gatsbym, takich jak pozyskiwanie danych, wdrażanie i wiele więcej.
```suggestion
   - [Przewodniki](/docs/guides/): Dowiedz się o wielu tematach związanych z budowaniem stron z Gatsby, takich jak pozyskiwanie danych, wdrażanie i wiele więcej.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +   - [API Gatsby'ego](/docs/api-reference/): Dowiedz się więcej o API Gatsby'ego i jego konfiguracji.
```suggestion
   - [API Gatsby](/docs/api-reference/): Dowiedz się więcej o API Gatsby i jego konfiguracji.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +   - [Przewodnik koncepcyjny](/docs/conceptual-guide/): Przeczytaj ogólny przegląd podejścia Gatsby'ego.
```suggestion
   - [Przewodnik koncepcyjny](/docs/conceptual-guide/): Przeczytaj ogólny przegląd podejścia Gatsb.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +   - [Profesjonalne korzystanie z Gatsby](/docs/using-gatsby-professionally/): Poznaj porady i wskazówki, jak wyjaśnić Gatsby'ego innym w pracy, aby mieć możliwość profesjonalnej pracy z Gatsbym.
```suggestion
   - [Profesjonalne korzystanie z Gatsby](/docs/using-gatsby-professionally/): Poznaj porady i wskazówki, jak wyjaśnić Gatsby innym w pracy, aby mieć możliwość profesjonalnej pracy z Gatsby.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +3. Sprawdź nasz [Ekosystem](/ecosystem/) bibliotek dla wtyczek i starterów Gatsby'ego, jak i zewnętrzne zasoby tworzone przez społeczność.
```suggestion
3. Sprawdź nasz [Ekosystem](/ecosystem/) bibliotek dla wtyczek i starterów Gatsby, jak i zewnętrzne zasoby tworzone przez społeczność.
```

2020-08-11 21:24 UTC, maciekgrzybek commented on docs/docs/index.md
> +Odwiedź sekcję [Współtowrzenia](/contributing/), by znaleźć przewodniki dla społeczności, kodeks postępowania, oraz jak zacząć współtworzyć Gatsby'ego.
```suggestion
Odwiedź sekcję [Współtowrzenia](/contributing/), by znaleźć przewodniki dla społeczności, kodeks postępowania, oraz jak zacząć współtworzyć Gatsby.
```

2020-08-11 21:29 UTC, mbiesiad commented on docs/docs/index.md
> +   - [Przewodnik koncepcyjny](/docs/conceptual-guide/): Przeczytaj ogólny przegląd podejścia Gatsby'ego.
'Gatsby' ofc.

2020-08-11 21:32 UTC, mbiesiad commented on docs/docs/index.md
> +   - [Przewodnik koncepcyjny](/docs/conceptual-guide/): Przeczytaj ogólny przegląd podejścia Gatsby'ego.
> 
last line (just a faint typo IMO):
'Gatsby' ofc.

2020-08-11 21:36 UTC, jakex7 commented on docs/docs/api-files-gatsby-node.md
> +  result.data.allSamplePages.edges.forEach((edge) => {
Oops, prawdopodobnie prettier zadziałał, niezamierzone.

2020-08-13 21:54 UTC, mbiesiad approved these changes

2020-10-13 14:41 UTC, AdamSiekierski requested changes

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +Gatsby to niesamowicie szybki, nowoczesny generator stron dla Reacta.
```suggestion
Gatsby to niesamowicie szybki i nowoczesny generator stron dla Reacta.
```

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +Istnieją dwie możliwości, by zacząć z Gatsby:
```suggestion
Z Gatsby możesz zacząć na dwa sposoby:
```

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +1. [Samouczek](/tutorial/): Instrukcje krok po kroku jak zainstalować Gatsby i rozpocząć swój projekt: napisane dla ludzi bez doświadczenia z Gatsby ani z programowaniem webowym, chociaż te zasoby po
Brzmi nieco nienaturalnie i nie-po-polsku ;)

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +## Następnie
Myślę, że lepiej byłoby użyć tu polskiego zwrotu "Co dalej?"

```suggestion
## Co dalej?
```

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +1. [Przykłady i dobre praktyki](/docs/recipes/): Znajdź kilka szybkich odpowiedzi, jak wykonywać typowe zadania z Gatsby.
Tutaj tłumaczymy to po prostu jako "przepisy"

```suggestion
1. [Przykłady i dobre praktyki](/docs/recipes/): Znajdź kilka szybkich odpowiedzi, jak wykonywać typowe zadania z Gatsby.
```

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +   - [Profesjonalne korzystanie z Gatsby](/docs/using-gatsby-professionally/): Poznaj porady i wskazówki, jak wyjaśnić Gatsby innym w pracy, aby mieć możliwość profesjonalnej pracy z Gatsby.
```suggestion
   - [Profesjonalne wykorzystywanie Gatsby](/docs/using-gatsby-professionally/): Poznaj porady i wskazówki, jak wyjaśnić Gatsby innym w pracy, aby mieć możliwość profesjonalnej pracy z Gatsby.
```

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/index.md
> +Odwiedź sekcję [Współtowrzenia](/contributing/), by znaleźć przewodniki dla społeczności, kodeks postępowania, oraz jak zacząć współtworzyć Gatsby.
```suggestion
Odwiedź sekcję [Kontrybucji](/contributing/), by znaleźć przewodniki dla społeczności, kodeks postępowania, oraz jak zacząć współtworzyć Gatsby.
```

2020-10-13 14:41 UTC, AdamSiekierski commented on docs/docs/api-files-gatsby-node.md
>  ---
Tego pliku chyba nie miałeś zamiaru dodać do tego PR'a :)

2021-03-14 23:12 UTC, derekqq requested changes

2021-03-14 23:12 UTC, derekqq commented on docs/docs/index.md
> +1. [Samouczek](/tutorial/): Instrukcje krok po kroku jak zainstalować Gatsby i rozpocząć swój projekt: napisane dla ludzi bez doświadczenia z Gatsby ani z programowaniem webowym, chociaż te zasoby po
Instrukcja krok po kroku jak zainstalować i zacząć pracę z projektem w Gatsby. Skierowana raczej dla osób bez doświadczenia z Gatsby czy tworzeniem stron internetowych, aczkolwiek te zasoby pomogły programistom na każdym poziomie zaawansowania. 

Coś takiego bym dał ;)

2024-12-12 10:08 UTC, closed without merging