Translate docs/node-apis
gatsbyjs/gatsby-pl pull request #53
Opened 2020-09-27 00:33 UTC by marceleq27

2020-09-27 08:17 UTC, AdamSiekierski requested changes
Kilka małych zmian :)

2020-09-27 08:17 UTC, AdamSiekierski commented on docs/docs/node-apis.md
> +description: Dokumentacja Node API wykorzystywanego przy procesie budowania do powszechnych zastosowań, takich jak tworzenie stron
Nieco dziwnie to brzmi :)

```suggestion
description: Dokumentacja Node API wykorzystywanego podczas budowania powszechnych zastosowań, takich jak generowanie stron
```

2020-09-27 08:17 UTC, AdamSiekierski commented on docs/docs/node-apis.md
> +Gatsby udostępnia wtyczkom i kreatorom stron wiele interfejsów API aby kontrolować przepływ danych za pośrednictwem GraphQL.
```suggestion
Gatsby udostępnia wtyczkom i kreatorom stron wiele interfejsów API umożliwiających kontrolowanie przepływu danych za pośrednictwem GraphQL.
```

2020-09-27 08:17 UTC, AdamSiekierski commented on docs/docs/node-apis.md
> +Jeśli twoja wtyczka wykonuje operacje asynchroniczne (dysk I/O, dostęp do bazy danych, wywoływanie zdalnych interfejsów API, etc.) musisz zwrócić obietnicę albo użyć funkcji zwrotnej przekazanej jako
`Promise`ów chyba nie tłumaczymy :D

```suggestion
Jeśli twoja wtyczka wykonuje operacje asynchroniczne (I/O na dyskach, dostęp do bazy danych, wywoływanie zdalnych interfejsów API, etc.) musisz zwrócić `Promise` albo użyć funkcji zwrotnej przekazanej jako trzeci argument. Gatsby musi wiedzieć kiedy wtyczki są gotowe, tak samo jak niektóre API aby zadziałać poprawnie - wymagają zakończenia pracy poprzednich interfejsów API. Sprawdź [Debugowanie asynchronicznych cykli życia](/docs/debugging-async-lifecycles/) aby dowiedzieć się więcej.
```

2020-09-27 21:09 UTC, marceleq27 commented
Dzięki za pomoc 👌  poprawione 🙂

2020-09-30 00:35 UTC, mbiesiad approved these changes

2020-10-13 14:10 UTC, AdamSiekierski approved these changes

2020-11-02 11:33 UTC, lekterable approved these changes

2020-11-02 11:33 UTC, merged