Translate graphql-api
gatsbyjs/gatsby-pl pull request #56
Opened 2020-11-01 17:32 UTC by marceleq27

2020-11-02 11:38 UTC, lekterable commented
Great work with the translations @marceleq27, I've merged the rest of your PR's and I'll try to find some time to look at this one in the upcoming days, thanks!

2020-11-02 18:08 UTC, AdamSiekierski requested changes
Trochę zmian, ale w większości małe. Pozmieniałem tłumaczenia niektórych słów i konstrukcje niektórych zdań na "bardziej polskie" :)

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Ogromną przewagą Gatsby jest wbudowana warstwa danych która łączy wszystkie źródła danych jakie skonfigurujesz. Dane są zbierane w [czasie kompilacji](/docs/glossary#build) i automatycznie zostają zg
Generalnie będę dawać zmiany dot. "naturalności" tłumaczenia. Samemu ciężko takie problemy znaleźć (a jeszcze trudniej rozwiązać), więc trzeba sobie pomagać :)

```suggestion
Ogromną przewagą Gatsby jest wbudowana warstwa danych która jest w stanie połączyć wiele źródeł danych. Dane zbierane są w [trakcie budowania](/docs/glossary#build) i zostają automatycznie zgromadzone w [schemat](/docs/glossary#schema) który definiuje w jaki sposób mogą one być pobierane przez twoją stronę.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Ten dokument służy jako odniesienie do funkcji GraphQL wbudowanych w Gatsby, włącznie z metodami do zapytań i pozyskiwania danych, oraz dostosowywania GraphQL do potrzeb twojej strony.
```suggestion
Jest to dokumentacja funkcjonalności GraphQL wbudowanych w Gatsby, włącznie z metodami do zapytań i pozyskiwania danych, oraz dostosowywania GraphQL do swoich potrzeb.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +GraphQL jest dostępny w Gatsby bez potrzeby dodatkowej instalacji: schemat jest automatycznie wyciągany i tworzony kiedy uruchamiasz projekt `gatsby develop` lub `gatsby build`. Kiedy strona zostanie
```suggestion
GraphQL jest dostępny w Gatsby bez potrzeby dodatkowej instalacji: schemat jest automatycznie budowany kiedy uruchamiasz projekt (`gatsby develop` lub `gatsby build`). Kiedy strona zostanie zbudowana, warstwę danych możesz [ręcznie przeglądać](/docs/running-queries-with-graphiql/) pod adresem: <http://localhost:8000/___graphql>

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Dane muszą być [pozyskane](/docs/content-and-data/) - lub dodane do schematu GraphQL - aby odpytać i wykorzystać je w stronach za pośrednictwem GraphQL. Gatsby wykorzystuje [wtyczki źródłowe](/plugin
Tutaj typowo konstrukcja z języka angielskiego ;)

```suggestion
Dane muszą zostać [dodane](/docs/content-and-data/) do schematu GraphQL, aby je odpytywać i wykorzystywać na stronie za pomocą GraphQL. Do pobierania danych, Gatsby wykorzystuje [wtyczki źródłowe](/plugins/?=gatsby-source).
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +**Uwaga**: GraphQL nie jest wymagany: możesz wciąż [wykorzystywać Gatsby bez GraphQL](/docs/using-gatsby-without-graphql/).
```suggestion
**Uwaga**: GraphQL nie jest wymagany: z Gatsby można [korzystać bez GraphQL](/docs/using-gatsby-without-graphql/).
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Aby pozyskać dane poprzez istniejącą wtyczkę, musisz zainstalować wszystkie potrzebne paczki. Ponadto musisz dodać wtyczkę do tablicy wtyczek w `gatsby-config` i jej opcjonalną konfigurację. Jeśli ch
```suggestion
Aby pozyskać dane poprzez istniejącą wtyczkę, musisz zainstalować wszystkie potrzebne paczki i dodać wtyczkę (oraz opcjonalnie jej konfigurację) do tablicy wtyczek w `gatsby-config`. Dane takie jak zdjęcia, pliki Markdown, itp. można pozyskiwać z systemu plików. Po więcej informacji, sprawdź [dokumentację pozyskiwania danych z systemu plików](/docs/sourcing-from-the-filesystem/) oraz [przepisy](/docs/recipes/sourcing-data).
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Możesz również [stworzyć niestandardowe wtyczki](/docs/creating-plugins/) aby pasowały do twoich przypadków użycia i wyciągaj dane jak tylko chcesz.
```suggestion
Możesz również [tworzyć niestandardowe wtyczki](/docs/creating-plugins/) dopasowane do twoich potrzeb, które mogą pobierać dane w dowolny sposób.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +## Odpytywanie w komponentach i hooki
```suggestion
## Komponenty i hooki służące do wykonywania zapytań
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +===========================================
Czo? :D

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +**Uwaga**: Ze względu na to jak Gatsby przetwarza zapytania GraphQL, nie możesz mieszać zapytań o strony i statycznych zapytać w tym samym pliku. Nie możesz również mieć wielokrotnych zapytań o stron
Tu nie chodzi o "zapytania o strony", a o specjalny typ zapytania zarezerwowany dla stron :)

```suggestion
**Uwaga**: Ze względu na to jak Gatsby przetwarza zapytania GraphQL, nie możesz mieszać zapytań stron i zapytań statycznych wewnątrz plik. Nie możesz również umieszczać wielu zapytań stron wewnątrz jednego pliku.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Po więcej informacji na temat komponentów strony lub innych w odniesieniu do zapytań, sprawdź przewodnik w dokumentacji [budowanie z komponentami](docs/building-with-components/#how-does-gatsby-use-r
```suggestion
Po więcej informacji na wykorzystywania przez Gatsby komponentów stron i nie tylko, sprawdź sekcję [budowanie z komponentami](docs/building-with-components/#how-does-gatsby-use-react-components).
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +`pageQuery` jest wbudowanym komponentem który pobiera informacje z warstwy danych w stronach Gatsby. Na jednej stronie możesz mieć jedno zapytanie. Może ono przyjmować argumenty GraphQL dla zmiennych
```suggestion
`pageQuery` jest wbudowanym komponentem który pobiera informacje z warstwy danych w stronach Gatsby. Na jednej stronie możesz mieć jedno zapytanie. Może ono przyjmować argumenty dla zmiennych w zapytaniach.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +[Strona jest utworzona w Gatsby](/docs/page-creation/) przez dowolny React komponent znajdujący się w folderze `src/pages` lub poprzez wywołanie akcji `createPage` oraz użycie komponentu w opcjach `c
```suggestion
[Strona jest utworzona w Gatsby](/docs/page-creation/) z dowolnego komponentu React znajdującego się w folderze `src/pages` lub poprzez wywołanie akcji `createPage` oraz użycie komponentu w opcjach `createPage` - znaczy to, że `pageQuery` nie zadziała w dowolnym komponencie, ale tylko w tych które spełniają te kryteria.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Zapoznaj się również z [przewodnikiem jak odpytywać dane w stronach poprzez zapytanie strony](/docs/page-query/)
```suggestion
Zapoznaj się również z [przewodnikiem dotyczącym pobierania danych w stronach poprzez zapytania stron](/docs/page-query/)

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +#### Zwroty
```suggestion
#### Zwrócone wartości
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Kiedy zapytanie jest użyte w pliku komponentu strony, zapytanie strony zwraca obiekt `data` który automatycznie jest przekazywany do komponentu jako atrybut.
```suggestion
Kiedy zapytanie jest użyte w pliku komponentu strony, zapytanie strony zwraca obiekt `data` zostaje przekazany do komponentu jako prop.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +StaticQuery jest wbudowanym komponentem który pobiera dane z warstwy danych Gatsby dla komponentów które nie są stronami, jak np. header, nawigacja czy dowolny inny komponent użyty jako dziecko.
```suggestion
StaticQuery jest wbudowanym komponentem który pobiera dane z warstwy danych Gatsby dla komponentów które nie są stronami, jak np. nagłówek, nawigacja czy dowolny inny komponent użyty jako dziecko.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Zapoznaj się również z [przewodnikiem jak odpytywać dane w komponentach wykorzystując zapytanie statyczne](/docs/static-query/).
```suggestion
Zapoznaj się również z [przewodnikiem dotyczącym odpytywania danych w komponentach wykorzystując zapytanie statyczne](/docs/static-query/).
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Komponent `StaticQuery` przyjmuje dwie wartości jako atrybuty w JSX:
```suggestion
Komponent `StaticQuery` przyjmuje dwie wartości jako propsy w JSX:
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Komponent StaticQuery zwraca `data` w jako atrybut `render`:
```suggestion
Komponent StaticQuery zwraca `data` argument w `render` prop:
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Hook `useStaticQuery` może być użyty podobnie do `StaticQuery` w dowolnym komponencie lub stronie, ale nie wymaga użycia komponentu i atrybutu render.
```suggestion
Hook `useStaticQuery` może być użyty w podobny sposób do `StaticQuery` w dowolnym komponencie lub stronie, ale nie wymaga użycia dodatkowego komponentu z render propem.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Ponieważ jest to React hook, [zasady korzystania z hooków](https://pl.reactjs.org/docs/hooks-rules.html) muszą zostać zachowane, więc będziesz potrzebował wersji React i ReactDOM 16.8.0 lub wyższej.
```suggestion
Ponieważ jest to React hook, [zasady korzystania z hooków](https://pl.reactjs.org/docs/hooks-rules.html) muszą zostać zachowane, więc będziesz potrzebować wersji React i ReactDOM 16.8.0 lub wyższej. Wobec tego to jak zapytania obecnie działają w Gatsby, tylko jedna instancja `useStaticQuery` jest wspierana dla danego pliku.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Zapoznaj się również z [poradnikiem jak odpytywać dane w komponentach z użyciem useStaticQuery](/docs/use-static-query/)
```suggestion
Zapoznaj się również z [poradnikiem dotyczącym odpytywania danych w komponentach z użyciem useStaticQuery](/docs/use-static-query/)
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Zapytania są pisane w takim samym kształcie w jakim mają być zwracane dane. Sposów w jaki pozyskujesz dane określi nazwy pól, w odniesieniu do których możesz wysyłać zapytania, na podstawie węzłów kt
Trochę nie po polsku ;)

```suggestion
Zapytania są pisane w takim samym kształcie w jakim mają być zwracane dane. Umieszczone dane określą nazwy pól do których możesz tworzyć zapytania, bazując na node'ach które dodają do schematu GraphQL.
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Różne węzły mogą przyjmować różne argumenty nw zależności od natury węzła
```suggestion
Różne node'y w zależności od ich budowy, przyjmować mogą różne argumenty
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Argumenty które możesz przekazać do kolekcji(jak tablice lub długie listy dancyh - np. `allFile` czy `allMdx`) to:
```suggestion
Argumenty które możesz przekazać do kolekcji (jak tablice lub długie listy danych - np. `allFile` czy `allMdx`) to:
```

2020-11-02 18:08 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Fragmenty pozwalają Ci na re-używanie części zapytań GraphQL. Pozwalają one również na dzielenie skomplikowanych zapytań na mniejsze, łatwiejsze w zrozumieniu komponenty.
```suggestion
Fragmenty pozwalają Ci na ponowne używanie części zapytań GraphQL. Pozwalają one również na dzielenie skomplikowanych zapytań na mniejsze, łatwiejsze w zrozumieniu komponenty.
```

2020-11-03 12:39 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +**Uwaga**: Ze względu na to jak Gatsby przetwarza zapytania GraphQL, nie możesz mieszać zapytań o strony i statycznych zapytać w tym samym pliku. Nie możesz również mieć wielokrotnych zapytań o stron
Tak dokładnie, nie wiedziałem do końca jak "page query" przetłumaczyć :P

2020-11-03 12:42 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +Hook `useStaticQuery` może być użyty podobnie do `StaticQuery` w dowolnym komponencie lub stronie, ale nie wymaga użycia komponentu i atrybutu render.
Sprawdzałem polską dokumentację reacta i tam propsy przetłumaczyli na atrybuty, może warto pozostać przy tym tłumaczeniu?

2020-11-03 12:43 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +Komponent StaticQuery zwraca `data` w jako atrybut `render`:
Tutaj podobnie (prop na atrybut)

2020-11-03 12:44 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +Komponent `StaticQuery` przyjmuje dwie wartości jako atrybuty w JSX:
Tutaj podobnie :)

2020-11-03 12:47 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +Kiedy zapytanie jest użyte w pliku komponentu strony, zapytanie strony zwraca obiekt `data` który automatycznie jest przekazywany do komponentu jako atrybut.
Tutaj podobnie :)

2020-11-03 12:52 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +**Uwaga**: Ze względu na to jak Gatsby przetwarza zapytania GraphQL, nie możesz mieszać zapytań o strony i statycznych zapytać w tym samym pliku. Nie możesz również mieć wielokrotnych zapytań o stron
Drobna poprawka, 'wewnątrz pliku' powinno być, poprawię już

2020-11-03 12:57 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +===========================================
Nie mam pojęcia 😅

2020-11-03 17:04 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Hook `useStaticQuery` może być użyty podobnie do `StaticQuery` w dowolnym komponencie lub stronie, ale nie wymaga użycia komponentu i atrybutu render.
Sprawdzę jeszcze raz jak tłumaczyliśmy tutaj, ale na 90% tłumaczyliśmy tutaj na propsy. Wydaje mnie się to bardziej naturalne niż "atrybuty", chociaż argument z dokumentacją Reacta ma jak najbardziej sens

2020-11-03 17:07 UTC, AdamSiekierski commented on docs/docs/graphql-api.md
> +Hook `useStaticQuery` może być użyty podobnie do `StaticQuery` w dowolnym komponencie lub stronie, ale nie wymaga użycia komponentu i atrybutu render.
Sprawdziłem, w innych tłumaczeniach jest `props` z polską odmianą :)

2020-11-03 17:11 UTC, marceleq27 commented on docs/docs/graphql-api.md
> +Hook `useStaticQuery` może być użyty podobnie do `StaticQuery` w dowolnym komponencie lub stronie, ale nie wymaga użycia komponentu i atrybutu render.
Okej, też mi się wydaje że jest to bardziej zrozumiałe niż atrybut, aczkolwiek zastanawiałem się jak bardzo chcemy być zgodni z innymi dokumentacjami :D, to już wszystko jasne :)

2020-11-03 17:12 UTC, marceleq27 commented
Poprawione wszystko, dzięki jeszcze raz za pomoc 🙂

2020-11-03 18:29 UTC, AdamSiekierski approved these changes

2020-11-03 23:42 UTC, lekterable approved these changes

2020-11-03 23:42 UTC, merged