Translate docs/api-files-gatsby-config
gatsbyjs/gatsby-pl pull request #60
Opened 2020-11-07 15:05 UTC by marceleq27

2020-11-07 15:46 UTC, AdamSiekierski requested changes

2020-11-07 15:46 UTC, AdamSiekierski commented on docs/docs/api-files-gatsby-config.md
> +Plik `gatsby-config.js` definiuje twoje metadane na stronie, wtyczki, oraz inną ogólną konfigurację. Plik ten powinien znajdować się w głównym katalogu twojej strony Gatsby.
```suggestion
W pliku `gatsby-config.js` zdefiniowane zostać mogą metadane twojej strony, wtyczki, oraz reszta ogólnej konfiguracji. Plik ten powinien znajdować się w głównym katalogu twojej strony Gatsby.

2020-11-07 15:46 UTC, AdamSiekierski commented on docs/docs/api-files-gatsby-config.md
> +Plik konfiguracyjny powinien eksportować obiekt JavaScript. W ramach tego obiektu możesz zdefiniować kilka różnych opcji konfiguracyjnych.
````suggestion
## Przygotowanie pliku konfiguracyjnego

Plik konfiguracyjny powinien eksportować obiekt JavaScript.  Wewnątrz tego obiektu możesz zdefiniować kilka różnych opcji konfiguracyjnych.
```

2020-11-07 15:46 UTC, AdamSiekierski commented on docs/docs/api-files-gatsby-config.md
> +## Przygotowanie pliku konfiguracyjnego
```suggestion
Jeżeli utworzyłeś/aś projekt strony korzystając z komendy `gatsby new`, domyślnie utworzony powinien zostać przykładowy plik konfiguracyjny.
```

2020-11-07 15:46 UTC, AdamSiekierski commented on docs/docs/api-files-gatsby-config.md
> +Jest [wiele dostępnych opcji konfiguracyjnych](/docs/gatsby-config), ale najczęstszym zestawieniem jest ustawienie metadanych oraz włączonych wtyczek.
```suggestion
[Opcji konfiguracyjnych](/docs/gatsby-config) jest naprawdę wiele, ale najczęściej konfiguracja ogranicza się do ustawienia metadanych strony oraz dodania wtyczek dla strony.
```

2020-11-07 15:46 UTC, AdamSiekierski commented on docs/docs/api-files-gatsby-config.md
> +Teraz [dostęp do tytułu strony możesz wykorzystać poprzez GraphQL](/tutorial/part-four/#your-first-graphql-query) w dowolnym miejscu na stronie.
```suggestion
Teraz [tytuł strony możesz uzyskać poprzez GraphQL](/tutorial/part-four/#your-first-graphql-query) w dowolnym miejscu na stronie.
```

2020-11-07 15:47 UTC, AdamSiekierski commented
Jest w porządku :D Poza tymi kilkoma zmianami, wygląda bardzo fajnie

2020-11-11 15:39 UTC, lekterable approved these changes

2020-11-11 15:40 UTC, merged