Translate docs/node-interface
gatsbyjs/gatsby-pl pull request #62
Opened 2020-11-08 18:05 UTC by marceleq27

2020-11-17 02:56 UTC, lekterable requested changes
Kilka małych poprawek z mojej strony i możemy mergować, daj znać co myślisz :)

2020-11-17 02:56 UTC, lekterable commented on docs/docs/node-interface.md
> +Klucz zazrezerwowany dla wtyczek które chcą rozszerzyć swoje node'y.
```suggestion
Klucz zarezerwowany dla wtyczek które chcą rozszerzyć swoje node'y.
```

2020-11-17 02:56 UTC, lekterable commented on docs/docs/node-interface.md
> +Wtyczka przez którą stworzony został node. To pole jest dodawane przez Gatsby(a nie przez wtyczkę).
```suggestion
Wtyczka, przez którą stworzony został node. To pole jest dodawane przez Gatsby (a nie przez wtyczkę).
```

2020-11-17 02:56 UTC, lekterable commented on docs/docs/node-interface.md
> +Magazyn informacji które wtyczki utworzyły poszczególne pola. To pole jest dodawane przez Gatsby(a nie przez wtyczkę).
```suggestion
Magazynuje informacje, które wtyczki utworzyły poszczególne pola. To pole jest dodawane przez Gatsby (a nie przez wtyczkę).
```

2020-11-17 02:56 UTC, lekterable commented on docs/docs/node-interface.md
> +- [Wtyczka przekształcająca dane(biblioteka Markdown)](/packages/gatsby-transformer-remark/) wyszukuje nowych node'ów,
```suggestion
- [Wtyczka przekształcająca dane (biblioteka Markdown)](/packages/gatsby-transformer-remark/) wyszukuje nowych node'ów,
```

2020-11-17 02:56 UTC, lekterable commented on docs/docs/node-interface.md
> +  transformację źródła YAML w obiekt JavaScript.
```suggestion
- [Wtyczka przekształcająca YAML](/packages/gatsby-transformer-yaml/) wyszukuje nowe node'y z typem nośnika `text/yaml` (np. pliki `.yaml`) i tworzy nowe YAML dzieci node'y poprzez transformację źródła YAML w obiekt JavaScript.
```

2020-11-17 11:07 UTC, marceleq27 commented
W sumie sądziłem, że będzie tego więcej bo dość ciężki artykuł do tłumaczenia 😄, ale wprowadziłem poprawki 🙂 Dzięki za pomoc 😛

2020-11-17 13:04 UTC, mbiesiad approved these changes, later dismissed
Approved with suggestions. Mainly few typos & uniform style.

2020-11-17 13:04 UTC, mbiesiad commented on docs/docs/node-interface.md
> +Klucz zarezerwowany dla wtyczek które chcą rozszerzyć swoje node'y.
Just small typo. Please use comma ',' before 'które'.

2020-11-17 13:04 UTC, mbiesiad commented on docs/docs/node-interface.md
> +"Node" jest centrum systemu danych Gatsby. Wszystkie dane które są dodane do Gatsby są modelowane wykorzystując node'y.
Just small typo. Please use comma ',' before 'które'.

2020-11-17 13:04 UTC, mbiesiad commented on docs/docs/node-interface.md
> +Opcjonalne pole dostarczające surową zawartość dla tego node'a którą mogą pobierać wtyczki przekształcające w celu dalszego przetwarzania.
Just small typo. Please use comma ',' before 'którą'.

2020-11-17 13:04 UTC, mbiesiad commented on docs/docs/node-interface.md
> +Nowe node'y dodawane są do Gatsby poprzez wtyczki "źródłowe". Powszechnie stosowaną przez wiele witryn Gatsby wtyczką źródłową jest [wtyczka źródłowa systemu plików](/packages/gatsby-source-filesyste
Just small typo. Please use comma ',' before 'która'.

2020-11-17 13:04 UTC, mbiesiad commented on docs/docs/node-interface.md
> +Gatsby automatycznie wprowadza strukturę node'ów Twojej strony i tworzy schemat GraphQL, który można następnie odpytywać z komponentów twojej strony.
Uniform style, "Twojej" vs "twojej". Preferred 'twojej' IMO, because of docs.

2020-11-17 14:18 UTC, mbiesiad commented on docs/docs/node-interface.md
> +Klucz zazrezerwowany dla wtyczek, które chcą rozszerzyć swoje node'y.
Typo: zazrezerwowany

Please fix to 'zarezerwowany'

2020-11-17 14:19 UTC, mbiesiad requested changes
Please fix new typo 'zazrezerwowany'

2020-11-17 14:25 UTC, mbiesiad approved these changes

2020-11-18 17:38 UTC, lekterable approved these changes

2020-11-18 17:38 UTC, merged