docs/recipes/sourcing-data translation
gatsbyjs/gatsby-pl pull request #65
Opened 2021-06-09 17:05 UTC by weronikadominiak

2021-06-09 19:14 UTC, mbiesiad requested changes
Please fix mentioned issues (ie. can't be typos here, in docs).

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +w ---
Probably 'missclick'. Please, remove.

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Do pozyskania danych w Gatsby używa się wtyczek, które pozyskują dane z określonych źrodeł (np. `gatsby-source-filesystem` pobiera dane z plików systemowych, `gatsby-source-wordpress` pobiera dane z
Please use "API" (that's the correct form, ie.: https://en.wikipedia.org/wiki/API).

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Do pozyskania danych w Gatsby używa się wtyczek, które pozyskują dane z określonych źrodeł (np. `gatsby-source-filesystem` pobiera dane z plików systemowych, `gatsby-source-wordpress` pobiera dane z
"samodzielnie" doubled here, please remove redundant one.

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +[Warstwa danych GraphQL](/docs/graphql-concepts/) wykorzystuje node'y, by zmodelować porcje danych. Wtyczki źródeł dodają źródłowe node'y, które możesz pozyskać poprzez wykonanie odpowiedniego zpayta
Typo (zpaytania). Need to be fixed, suggested:
zapytania

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +   > _Uwaga: Po dokonaniu zmian w `gatsby-node.js` muisz ponownie uruchomić komendę `gatsby develop` aby zaobserwować te zmiany._
Typo (muisz). Please change to 'musisz'.

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Wykonaj zapytanie (w GraphiQL lub w Twoim komponencie).
If I'm not mistaken, here should be 'twoim' used (written with lowercase letters). But it should be confirmed if nothing has changed.

2021-06-09 19:14 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +## Pozyskiwanie danych z Markdownu dla blog postów i stron z GraphQL
"blog postów" should be changed.

2021-06-09 20:19 UTC, mbiesiad requested changes

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +## Pozyskiwanie danych z Markdownu dla blog postów i stron z GraphQL
Actually, it would be great to change a little bit, like 'wraz z GraphQL' or 'korzystając z GraphQL'.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Możesz pozyskać dane z Markdownu i użyć [`createPages` API](/docs/actions/#createPage) by dynamicznie stworzyć strony.
'aby' could be better IMO, anyway, comma needed here.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Ten przepis pokazuje w jaki sposób z plikow Markdown ulokowanych na twoim lokalnym systemie stworzyć strony z użyciem warstwy danych GraphQl.
plikow -> plików
previously used 'Twoim', here 'twoim', must be unified.
GraphQl -> GraphQL

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +### Wymagania
Wymagania wstępne

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +1. Do pliku `gatsby-config.js`, dodaj `gatsby-transformer-remark` i `gatsby-source-filesystem` by pobrać dane z plików Markdown znajdujących się w folderze `source`. Będzie to dodatkiem do poprzednic
'by pobrać dane' -> 'aby pobrać dane' sounds better IMO, anyway comma needed.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +1. Do pliku `gatsby-config.js`, dodaj `gatsby-transformer-remark` i `gatsby-source-filesystem` by pobrać dane z plików Markdown znajdujących się w folderze `source`. Będzie to dodatkiem do poprzednic
Before 'jak' also comma needed.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +2. Dodaj post z użyciem Markdownu w `src/content`, zawżyj frontmatter dla: tytułu, daty i ścieżki. Dodaj początkowy kontent do body posta:
Just a quick note, please be sure if we are changing the words' ​forms here (Markdownu vs Markdown, etc)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +2. Dodaj post z użyciem Markdownu w `src/content`, zawżyj frontmatter dla: tytułu, daty i ścieżki. Dodaj początkowy kontent do body posta:
kontent -> zawartość
(by the way, suggested "zawżyj" -> "zawierając"; other tense etc)
'Dodaj początkowy kontent do body posta' need to be changed.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski komendą `gatsby develop`. Następnie przejdź to exploratora GraphiQL `http://localhost:8000/___graphql` i wykonaj zapytanie o dane z plikow Markdown:
Need to be changed - "developerski "

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski komendą `gatsby develop`. Następnie przejdź to exploratora GraphiQL `http://localhost:8000/___graphql` i wykonaj zapytanie o dane z plikow Markdown:
Also for change: "Następnie przejdź **to exploratora** GraphiQL"

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski komendą `gatsby develop`. Następnie przejdź to exploratora GraphiQL `http://localhost:8000/___graphql` i wykonaj zapytanie o dane z plikow Markdown:
Change: z **plikow** Markdown + previously used ~'Markdowna'. I'm pretty sure that should be used "Markdown" as here.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +5. Dodaj szablon dla posta w folderze `src/templates` i umieść w nim zapytanie GraphQl by dynamicznie wygenerować strony z Markdownu w trakcie kompilacji:
GraphQl -> GraphQL (+ comma before 'aby/by')

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +5. Dodaj szablon dla posta w folderze `src/templates` i umieść w nim zapytanie GraphQl by dynamicznie wygenerować strony z Markdownu w trakcie kompilacji:
Used different forms, once 'Markdownu', other time 'Markdown', please change.

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +6. Wykonaj komendę `gatsby develop` by uruchomić ponownie serwer developerski. Sprawdź swój post w przeglądarce: `http://localhost:8000/my-first-post`
'by uruchomić' comma "," needed before aby/by

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +6. Wykonaj komendę `gatsby develop` by uruchomić ponownie serwer developerski. Sprawdź swój post w przeglądarce: `http://localhost:8000/my-first-post`
Change for 'developerski' needed

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +### Wymagania
Wymagania wstępne

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +> **Uwaga:** Sprawdź [dokumentację wtyczki `gatsby-source-wordpress`](/packages/gatsby-source-wordpress/?=wordpre#how-to-use) by dowiedzieć się więcej o tym, jak ją prawidłowo skonfiugurować.
Comma ',' needed before 'by/aby'

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +> **Uwaga:** Sprawdź [dokumentację wtyczki `gatsby-source-wordpress`](/packages/gatsby-source-wordpress/?=wordpre#how-to-use) by dowiedzieć się więcej o tym, jak ją prawidłowo skonfiugurować.
Typo with 'skonfiugurować'

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +5. Uruchom komendę `gatsby-develop` żeby zobaczyć nowo wygenerowane strony i poruszać się pomiędzy nimi.
Comma ',' needed before 'by/aby/żeby'

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +6. Otwórz`GraphiQL IDE` pod adresem `http://localhost:8000/__graphql` i otwórz Docs lub Explorer, gdzie znajdziesz pola do opytywania dla `allWordpressPosts`
Typo with 'opytywania'

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Stworzone powyżej w `gatsby-node.js` dynamiczne strony mają unikalne ścieżki dla poszczególnych postów i używają szablonu razem z przykładowym zapytaniem GraphQl, które pozyskuje dane z Wordpressa.
GraphQl -> GraphQL
Wordpressa vs Wordpress (unifined, changing forms or not)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +- Więcej o [pozyskiwaniu danych z WordPressa](/docs/sourcing-from-wordpress/)
**Wordpressa** vs Wordpress (unifined, changing forms or not)
Below, used "danych z **WordPress**"...

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +### Wymagania
Wymagania -> requirements.
here, missing: "wstępne"

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +1. Zaloguj się do Contenful przez CLI i postępuj zgodnie z kolejnymi krokami. Jeśli nie masz jeszcze konta, CLI umożliwi Ci założenie nowego.
"ci". previosuly used lower case (unify)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Uwaga: jeśli stworzyłeś nowe konto, możesz nadpisać domyślny space. Sprawdź [spaces zawarte w Twoim koncie](https://app.contentful.com/account/profile/space_memberships).
Case sensitive with 'Twoim' (previously mentioned)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +4. Stwórz nowy klucz dostępu dla twojego space. Zapamiętaj ten klucz, będzie on potrzebny w 6tym kroku.
Change: 6tym

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +8. Wykonaj zapytanie za pomocą [edytora GraphiQL](/docs/introducing-graphiql/) pod adresem `http://localhost:8000/___graphql`. Wtyczka Contentful dodaje kilka nowych typów node'ów, włączając wszystke
GraphQl to GraphQL for instance

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +![Interferjs graphQL, z przykładowym zapytaniem przedstawionym poniżej](../images/recipe-sourcing-contentful-graphql.png)
graphQL -> GraphQL
https://graphql.org/

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +- [Tworzenie strony z użyciem Reacta o Contentful](/blog/2018-1-25-building-a-site-with-react-and-contentful/)
Reacta -> React
like (...) Gatsby'iego -> (...) Gatsby

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +- [Wtyczka źródła Contentful ](/packages/gatsby-source-contentful/)
"Wtyczka źródła Contentful " (redundant 'space' here, after 'Contentful').

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +- [Typy pól z długim tekstem zwracane jako obiekty](/packages/gatsby-source-contentful/#a-note-about-longtext-fields)
Before 'jako', please use comma ','

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +## Pozyskiwanie danych z zewnętrznych źródeł i tworzenie stron bez użycia GrapohQL
Typo: GrapohQL

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +Nie musisz używać warstwy danych GraphQl, aby uwzględnić dane na stronach, [chociaż są istotne powody, dla których powinieneś rozważyć użycie GraphQL](/docs/why-gatsby-uses-graphql/). Możesz wykorzys
GraphQl -> GraphQL, typo

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +W tym przepisie utworzysz dynamiczne strony z danych pobranych z [endpointów PokéAPI’s REST](https://www.pokeapi.co/). [Kompletny przykład](https://github.com/jlengstorf/gatsby-with-unstructured-data
Githubie -> GitHub

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +### Wymagania
'wstępne' needed

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +1. Dodaj poniższy kod do pliku `gatsby-node.js` by pobrać dane z PokeAPI i programowo stworzyć stronę główną:
Comma ',' needed (by)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +2. Stwórz szablon aby wyświetlić Pokémony na stronie głównej:
Comma ',' needed (aby)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom komendę `gatsby develop` by pozyskać dane, zbudować strony i uruchomić serwer developerski.
The same, comma ',' needed (by)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom komendę `gatsby develop` by pozyskać dane, zbudować strony i uruchomić serwer developerski.
"developerski" for change

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +- Więcej o nieustrukturyzowanych danych w samouczku o [używaniu Gatsby bez GraphQl](/docs/using-gatsby-without-graphql/)
GraphQl -> GraphQL https://graphql.org/

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +### Wymagania
'wstępne'

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +- [JSON:API moduł](https://www.drupal.org/project/jsonapi) zainstalowany i aktywowany na Drupal
rearrange the words ('moduł' first)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +2. Dodaj poniższy kod do pliku `gatsby-config.js` by skonfigurować i aktywować wtyczkę.
Comma ',' needed before 'by/aby'

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski przy użyciu komendy `gatsby develop`, otwórz eksplorator GraphiQL pod adresem `http://localhost:8000/___graphql`.
Change: developerski

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski przy użyciu komendy `gatsby develop`, otwórz eksplorator GraphiQL pod adresem `http://localhost:8000/___graphql`.
Change: "i eden dla każdego"

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski przy użyciu komendy `gatsby develop`, otwórz eksplorator GraphiQL pod adresem `http://localhost:8000/___graphql`.
Twoim -> twoim

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski przy użyciu komendy `gatsby develop`, otwórz eksplorator GraphiQL pod adresem `http://localhost:8000/___graphql`.
Comma needed; jeśli

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +3. Uruchom serwer developerski przy użyciu komendy `gatsby develop`, otwórz eksplorator GraphiQL pod adresem `http://localhost:8000/___graphql`.
Typo: poniżego

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +_**Uwaga:** dokładna schema GraphQL będzie zależała od tego jak skonfigurowana jest Twoja instancja Drupal._
twoja + comma "," (jak)

2021-06-09 20:19 UTC, mbiesiad commented on docs/docs/recipes/sourcing-data.md
> +5. Mając uruchomiony serwer developerski możesz zobaczyć swoją nową stronę odwiedzając `http://localhost:8000/drupal`
Change: developerski

2021-06-10 09:25 UTC, weronikadominiak commented
@mbiesiad Thank you for the great review! Yes of course, it can't have typos! I've replaced "by" with "aby", added a few more missing commas. Changed all Wordpress and Markdown to always use original form.

2021-06-10 10:42 UTC, mbiesiad commented
@weronikadominiak Sounds awesome! 🎉 Your work was great as well! I will take a look ASAP (pm/evening). Let's keep in touch, best wishes

2021-06-30 13:59 UTC, weronikadominiak commented
Closing due to https://github.com/gatsbyjs/gatsby-pl/issues/1#issuecomment-860053367

2021-06-30 13:59 UTC, closed without merging